# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  lane :release do

  	increment_version_code(
  		gradle_file_path: "version.properties"
  	)

  	gradle(
  		task: "app:assembleRelease"
  	)

  	#appcenter_upload(
    #	api_token: ENV['APPCENTER_API_TOKEN'],
    #	owner_name: "TamasVarga",
    #	app_name: "Rates",
    #	notify_testers: false,
    #	destinations: "All-users-of-Rates",
    #	apk: Actions.lane_context[Actions::SharedValues::GRADLE_APK_OUTPUT_PATH],
    #	dsym: "./app/build/outputs/mapping/release/mapping.txt"
    #)

    hockey(
    	api_token: ENV['HOCKEY_APP_TOKEN'],
    	notes: "Latest Rates app",
    	notify: "2",
    	status: "2",
    	apk: Actions.lane_context[Actions::SharedValues::GRADLE_APK_OUTPUT_PATH],
    	dsym: "./app/build/outputs/mapping/release/mapping.txt",
    	public_identifier: "1706a6bc8d114624a7097aec9813c9c3"
    )

  end

  lane :increment_version do

  	increment_version_code(
  		gradle_file_path: "version.properties"
  	)

  end

end